language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: EmuGM+idrxg3DDqjzad1p/Zj+gDb7Y7zuz4S2AA3mhPUg/YNUJivyPXvzSr38Qr8Z9R1ZJieXbmEg55sRJBA+hxtmFDaWeKtNb1dG5w8tMN3fr6FcUvgxwLkSAIHLhTb9CbZwGUp4BSDsbbCQFhR/zBNhN5PdZxP3u1+KQKxnio=
  - secure: OrRu9ScaJBKCCoD/EEcbY+w/KNzwXnN3EHNZ3X/Zyuuo0ybbCD/TonRw8cdg2BFzd1CpxQ0KLsRg4HcEsW+EfqkQWyKZS6qXTPKzAcN3dULgXpwEkLn66FWaKXhgOhj+662RekWxYuN95uQ1HYxN5k1t1yqNqjCzBL9qViwO/9M=
  - secure: Ds/S7AuY2gCdViMelydnEch/q58IW470ChfSbQaFu8nakcdWw7F/n7weVaDUuBCnsjnZggHDi+rKlQiC/d9PiER11a5D42SZr2HX1zgS3PYUvVW6f0pEUeZ2/bx6aEeFmAQcXuQCIqYRkwMmKd2QdCOqJ9/jIcO6T3hkGfisNeY=
  - secure: rWeXyAzjqdD7Fbm7d1ii79HxFjOVHhg98L9ByGZvHYQkuTX9uOPhCy363XLG8pvLEU8ZGmAp1rD8QJesQFf6OdwObfpL4sv8yW4Ayd82nzG4+3eyboKS4e1gmoUv0MCfBoeMchAGOUPdKwf55xpnW3biWkY0HBlT3meKptwdLVI=
